### ISSUE TITLE
Better integration with AssertJ 2.0 

### ISSUE THREAD

**Issue by mariuszs** [Codearte/catch-exception#20]
What do you think about this usage:

```java
@Test
public void testName() throws Exception {
    // given an empty list
    List myList = new ArrayList();

    // we are recording exception here
    when(myList).get(1);

    // and then rethrowing for verification
    thenThrownBy(CatchException::rethrow) 
            .isInstanceOf(IndexOutOfBoundsException.class);
}
```

This allows migrating existing catch-exception code to Java 8 and AssertJ with minimal effort.

**Comment by szpak** [comment]
Nice idea!

Btw, would it be good to have also an integration tests for it.
Btw2, a version for `Throwable` could be also added.

**Comment by mariuszs** [comment]
This is not needed now, because standard way is workin with Java8

```java
when(myList).get(1);

then(caughtException()) 
            .isInstanceOf(IndexOutOfBoundsException.class);
```

**Comment by mariuszs** [comment]
Leave a comment, if you still think that this can be useful :)

**Comment by szpak** [comment]
Haven't tried. I already use Spock or AssertJ 2.0 directly.

**Comment by mariuszs** [comment]
To na pewno wazna informacja dla wszystkich, ale pytalem sie czy uwazasz ze
to ciagle jest uzyteczna funkcja. Zwrócê uwagê ¿e sam stwierdzi³e¶ ze to
"Nice idea", wiec chyba masz jakies zdanie na ten temat ;)

On Sat, Apr 4, 2015 at 8:04 AM, Marcin Zaj±czkowski <
notifications@github.com> wrote:

> Haven't tried. I already use Spock or AssertJ 2.0 directly.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Codearte/catch-exception/issues/20#issuecomment-89510153>
> .
>



-- 
Mariusz Smyku³a
