### ISSUE TITLE
Catch-Exception 2.0 Ideas

### ISSUE THREAD

**Issue by mariuszs** [Codearte/catch-exception#21]
Full integration with AssertJ 2.0

``` java
import static com.googlecode.catchexception.apis.BDDCatchException.*;
import static org.assertj.core.api.BDDAssertions.then;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

public class AssTest {

    @Test
    public void testName() throws Exception {
        // given an empty list
        List myList = new ArrayList();

        // when we try to get first element of the list
        when(() -> myList.get(1));

        then(caughtException())
                .isInstanceOf(IndexOutOfBoundsException.class);
    }

}
```
- No proxing, 
- Java8 and AssertJ API only,
- without conflict with BDDAssertions.then in single class

**Comment by RobWin** [comment]
+1 :)

**Comment by hazendaz** [comment]
Is any work currently being performed on version 2?  I certainly can start helping out where needed.

**Comment by mariuszs** [comment]
I think we should go forward with this, maybe this is time for beta?

**Comment by hazendaz** [comment]
I'm sure 2.x needs some spring cleaning.  I can bring up to date tonight then beta sounds good.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by mariuszs** [comment]
it is done ;) Thanks to everyone :)
