### ISSUE TITLE
Catch exceptions directly in the expected type

### ISSUE THREAD

**Issue by sedubois** [Codearte/catch-exception#23]
I have a custom `BusinessRuleException` with an extra method `getCode()`. With catch-exception 1.4.2, my tests look like this (didn't find a better way):

```
when(service).doSomething();

then(caughtException()).isInstanceOf(BusinessRuleException.class);
BusinessRuleException e = (BusinessRuleException) caughtException();
then(e.getCode()).isEqualTo(MY_ERROR_CODE);
```

This has 2 issues:
- on the third line, where `caughtException()` is called, IntelliJ IDEA 14.1 warns that I get an exception which is not rethrown
- not fluent

I would expect to be able to write something like (or some variation with better API and taking into account what's required to avoid unchecked casts and whatnot):

```
when(service).doSomething();

then(caughtException())
    .isInstanceOfAndGet(BusinessRuleException.class)
    .getCode().isEqualTo(MY_ERROR_CODE);
```

**Comment by mariuszs** [comment]
We are using AssertJ now, so you can easily write custom assertions for your business exception http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html.

Please show your code for catch-exception before 1.4.2.

I take look into Intellij warning...

**Comment by mariuszs** [comment]
Ok, custom assertion dosent help here. I need to think about this :) Thanks for the report

**Comment by mariuszs** [comment]
I have only one solution to this problems -> 
https://github.com/mariuszs/catch-exception/commit/2b9ff7ac61b83fcd62d415545b7fdacfb9607240

```java
 thenCaughtException()
                .isInstanceOf(IndexOutOfBoundsException.class) //
                .hasMessage("Index: 1, Size: 0") //
                .hasNoCause();
```

**Comment by mariuszs** [comment]
Fixed in #27

**Comment by mariuszs** [comment]
I leave old behaviour for Java 6 and 7, for Java 8 this is not working, my proposition for java 8:

```java
when(service).doSomething();

then(caughtException((BusinessRuleException.class))
    .isInstanceOfAndGet(BusinessRuleException.class)
    .getCode().isEqualTo(MY_ERROR_CODE);
```

3f0db0678200051ab273f082649d593269629444

**Comment by sedubois** [comment]
Is clearly better, but 
```
then(caughtException(BusinessRuleException.class))
.isInstanceOfAndGet(BusinessRuleException.class)
``` 
still very much looks like code duplication. `isInstanceOfAndGet()` should be automatically done inside the `then(caughtException())` or similar.

**Comment by mariuszs** [comment]
You are absolutly right, but I dont know how to do that (for Java8).

http://stackoverflow.com/questions/29499847/ambiguous-method-in-java-8-why

**Comment by mariuszs** [comment]
You can do something like this 

https://github.com/Codearte/catch-exception/blob/2.x/catch-exception/src/test/java/com/googlecode/catchexception/test/apis/BDDCustomCatchExceptionTest.java

**Comment by evilmilo** [comment]
Can we get a non-generic version of caughtException() added?

At moment the signature is

    public static <E extends Exception> E caughtException()

java 8 is now more strict, and requires the caller to define that type.  Where method overloading means multiple parameters could match, you now get the ambiguity error.

for most of the assert frameworks, we just want to pass Exception in.  so it would be handier if the method signature was just:

    public static Exception caughtException()

Which would remove the ambiguity.  To avoid breaking existing code, could either add non generic  method with different name, or create a new parallel class that doesn't use the generics.

**Comment by mariuszs** [comment]
Sorry for delay, I missed your answer,

I have added `Exception caughtException()` to `BDDCatchException`

Btw, we can use something like `org.assertj.core.api.AssertionsForClassTypes' in Java8 with non-generic caughtException().
