### ISSUE TITLE
outdated documentation

### ISSUE THREAD

**Issue by tomekkaczanowski** [Codearte/catch-exception#36]
Hello,

docs at https://github.com/Codearte/catch-exception/wiki/Installation seems to be outdated.

Would be nice to update them to 1.4.4 and to mention it works with Mockito 1.10.19 - at least for me :)

Regards,
Tomek Kaczanowski

**Comment by jkubrynski** [comment]
Thanks Tomek, we'll cover it shortly. But to be seroius,  looking at your
writing talent I would expect pull request ;-)

**Comment by barbraz** [comment]
Hi,

you could also update the [README.md](https://github.com/Codearte/catch-exception/blob/master/README.md), because currently in BDD-like section it encourages to use a deprecated method.

Cheers,
B.

**Comment by mariuszs** [comment]
thanks
