### ISSUE TITLE
Which Maven dependency should I use?

### ISSUE THREAD

**Issue by mcandre** [Codearte/catch-exception#39]
The catch-exception libs on Maven Central look really out of date compared to the development on this catch-exception git repo. Which org, artifact name, and version should we use? Google, EU?

**Comment by mariuszs** [comment]
Latest stable version is 1.4.4

http://mvnrepository.com/artifact/eu.codearte.catch-exception/catch-exception

```xml
<dependency>
	<groupId>eu.codearte.catch-exception</groupId>
	<artifactId>catch-exception</artifactId>
	<version>1.4.4</version>
</dependency>
```
