### ISSUE TITLE
Better error when mocking a final class

### ISSUE THREAD

**Issue by mcandre** [Codearte/catch-exception#41]
When a user accidentally applies CatchException to an object whose class is final, CatchException should show a better error message along the lines of "Unable to mock final class`, so that the user has a better idea of why the ClassCastException occurs.

**Comment by mariuszs** [comment]
I will close this issue because catch-exception 1.x is no longer under development and 2.x has no more problems with mocking (it is not relying on mockito but requires java 8 and is using lambdas).
