### ISSUE TITLE
Handling runtime exceptions

### ISSUE THREAD

**Issue by dmitrysenkovich** [Codearte/catch-exception#46]
Hello everyone,
Just an offer: how about adding handling runtime exceptions? I'm working on E2E tests where it can be helpful.
Thanks!

**Comment by mariuszs** [comment]
We already have support for runtime exceptions, can you tell more about your idea?

**Comment by dmitrysenkovich** [comment]
@mariuszs Seems like I was mistaken then:) I'm trying to catch an exception and it doesn't work for me. It my problem only then, sorry. Thanks so such a quick response!
